name: deep_wa
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.13
  - ipykernel==6.15.1
  - cudatoolkit==11.3.1
  - cudnn=8.2.1.32
  - tensorflow-gpu==2.6.0
  - tensorflow-estimator==2.6.0
  - numpy==1.23.1
  - pandas==1.4.3
  - matplotlib==3.5.2
  - seaborn==0.11.2
  - scikit-learn==1.1.1
  - h5py==3.7.0
  - gensim==4.2.0

