name: deep_wa
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.0
  - ipykernel==6.15.1
  - cudatoolkit==11.2.0 # REMOVE this line if no GPU available
  - cudnn==8.1.0.77 # REMOVE this line if no GPU available
  - numpy==1.23.1
  - pandas==1.4.3
  - matplotlib==3.5.2
  - seaborn==0.11.2
  - scikit-learn==1.1.1
  - h5py==3.7.0
  - gensim==4.2.0
  - pip==22.2.2  
  - pip:
    - tensorflow==2.9.1 
    - tensorflow-estimator==2.9.0

