name: deep_wa_bert
channels:
  - huggingface
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - ipykernel
  - pytorch
  - transformers
  - datasets
  - cudatoolkit
  - pandas
  - numpy
  - matplotlib
  - gensim
  - scikit-learn 
